[project]
name = "colrev.pdf_backward_search"
description = "CoLRev package for pdf_backward_search"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/pdf_backward_search"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Backward search extracting references from PDFs using GROBID"
colrev_doc_link = "README.md"
search_types = ["BACKWARD_SEARCH"]

[project.entry-points.colrev]
search_source = "colrev.packages.pdf_backward_search.src.pdf_backward_search:BackwardSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
