[project]
name = "colrev.blank"
description = "CoLRev package for blank_review"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/blank"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Blank Review"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points.colrev]
review_type = "colrev.packages.blank.src.blank:BlankReview"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
