name: Run colrev update

on:
  workflow_dispatch:
  schedule:
    - cron: '10 2 * * *'

# Note : requires github/settings/actions/general/workflow permissions/read and write
# Note : requires github/settings/actions/general/workflow permissions/create and approve pull requests
# Note : pr_body should contain the code that was run and the potential errors

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
      - run: |
          pip install git+https://github.com/CoLRev-Environment/colrev.git#egg=colrev
      - run: |
          git config user.name "CoLRev update"
          git config user.email "actions@users.noreply.github.com"
          git config --global url.https://github.com/.insteadOf git://github.com/
          git branch colrev-update
          git checkout colrev-update
          colrev search -f
          colrev load
          colrev prep
          colrev prep --polish
          colrev dedupe
          colrev prescreen
          colrev pdfs
          colrev screen
          git push --set-upstream origin colrev-update
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "colrev-update"
          destination_branch: "main"
          pr_title: "Pull colrev search updates"
          pr_body: |
            *CoLRev updates*

            _Created by [colrev gh-action updater](https://github.com/CoLRev-Environment/colrev/tree/main/colrev/template)_
