[project]
name = "colrev.ais_library"
description = "CoLRev package for aisel"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/ais_library"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "AIS electronic Library (AISeL)"
colrev_doc_link = "README.md"
search_types = ["DB", "API", "TOC"]

[project.entry-points.colrev]
search_source = "colrev.packages.ais_library.src.aisel:AISeLibrarySearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
