[project]
name = "colrev.files_dir"
description = "CoLRev package for files_dir"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/files_dir"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Files directories (PDFs based on GROBID)"
colrev_doc_link = "README.md"
search_types = ["FILES"]

[project.entry-points.colrev]
search_source = "colrev.packages.files_dir.src.files_dir:FilesSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
