[project]
name = "colrev.website_screenshot"
description = "CoLRev package for website_screenshot"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/website_screenshot"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Website Screenshot"
colrev_doc_link = "README.md"
search_types = []

[project.entry-points.colrev]
pdf_get = "colrev.packages.website_screenshot.src.website_screenshot:WebsiteScreenshot"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
