[project]
name = "colrev.ieee"
description = "CoLRev package for ieee"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Rhea Nguyen" },
    { name = "Malou Schmidt" },
    { name = "Frederic Fischer" },
    { name = "Janus Fiegen" },
    { name = "Albert Borchardt" },
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" },
]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/ieee"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "IEEEXplore"
colrev_doc_link = "README.md"
search_types = ["API"]

[project.entry-points.colrev]
search_source = "colrev.packages.ieee.src.ieee:IEEEXploreSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
