[project]
name = "colrev.importer"
description = "Package facilitating the import of literature review data from other projects"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
dependencies = [
    "bib-dedupe>=0.7.6",
]

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/"

[project.scripts]
colrev-importer = "colrev.packages.importer.src.importer:main"

[[tool.poetry.packages]]
include = "src"

[tool.colrev]
colrev_doc_description = "TODO"
colrev_doc_link = "docs/README.md"
search_types = []

[project.entry-points.colrev]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
