[project]
name = "colrev.ebsco_host"
description = "CoLRev package for ebsco_host"
version = "0.1.0"
license = "MIT"
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/ebsco_host"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "EBSCOHost"
colrev_doc_link = "README.md"
search_types = ["DB"]

[project.entry-points.colrev]
search_source = "colrev.packages.ebsco_host.src.ebsco_host:EbscoHostSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
