[project]
name = "colrev.open_alex"
description = "CoLRev package for open_alex"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
dependencies = [
    "pyalex>=0.10"
]

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/open_alex"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "OpenAlex API"
colrev_doc_link = "README.md"
search_types = ["API", "MD"]

[project.entry-points.colrev]
search_source = "colrev.packages.open_alex.src.open_alex:OpenAlexSearchSource"
prep = "colrev.packages.open_alex.src.open_alex_metadata_prep:OpenAlexMetadataPrep"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
