[project]
name = "colrev.arxiv"
description = "CoLRev package for arxiv"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"
dependencies = [
    "feedparser>=6.0.10"
]

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/arxiv"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "arXiv"
colrev_doc_link = "README.md"
search_types = ["API"]

[project.entry-points.colrev]
search_source = "colrev.packages.arxiv.src.arxiv:ArXivSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
