[project]
name = "colrev.dblp"
description = "CoLRev package dblp"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/dblp"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "DBLP API"
colrev_doc_link = "README.md"
search_types = ["API", "TOC", "MD"]

[project.entry-points.colrev]
search_source = "colrev.packages.dblp.src.dblp:DBLPSearchSource"
prep = "colrev.packages.dblp.src.dblp_metadata_prep:DBLPMetadataPrep"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
