[project]
name = "colrev.open_citations_forward_search"
description = "CoLRev package for open_citations_forward_search"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/open_citations_forward_search"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Forward search based on OpenCitations"
colrev_doc_link = "README.md"
search_types = ["FORWARD_SEARCH"]

[project.entry-points.colrev]
search_source = "colrev.packages.open_citations_forward_search.src.open_citations_forward_search:OpenCitationsSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
