[project]
name = "colrev.prospero"
description = "ColRev package for Prospero"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Ammar Al-Balkhi", email = "ammar.al-balkhi@stud.uni-bamberg.de" },
    { name = "Phuc Tran", email = "tra-thien-phuc.tran@stud.uni-bamberg.de" },
    { name = "Olha Komashevska", email = "olha.komashevska@stud.uni-bamberg.de" },
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" },
]
requires-python = ">=3.8, <4"
dependencies = [
    "selenium>=4.27.1"
]

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "Prospero"
colrev_doc_link = "docs/README.md"
search_types = ["API"]

[project.entry-points.colrev]
search_source ="colrev.packages.prospero.src.prospero_search_source:ProsperoSearchSource"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
