name: Publish to PyPI.org
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  pypi:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version with caching
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11

      - name: Install the project
        run: uv sync --all-extras

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
