name: Update requirements.txt

on:
  schedule:
    - cron: '0 5 * * 1'  # Every Monday at 5:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Update requirements.txt
        run: uv pip compile --all-extras --output-file=requirements.txt

      - name: Commit & PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update requirements.txt from pyproject.toml"
          branch: update/requirements
          title: "Update requirements.txt"
          body: |
            Automated update of `requirements.txt` from `pyproject.toml` using `uv`.
          delete-branch: true
