[project]
name = "colrev.synergy_datasets"
description = "CoLRev package for SYNERGY Datasets"
version = "0.1.0"
license = {text = "MIT"}
authors = [
    { name = "Gerit Wagner", email = "gerit.wagner@uni-bamberg.de" }
 ]
requires-python = ">=3.8, <4"

[project.urls]
repository = "https://github.com/CoLRev-Environment/colrev/tree/main/colrev/packages/synergy_datasets"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.colrev]
colrev_doc_description = "SYNERGY Datasets"
colrev_doc_link = "README.md"
search_types = ["API"]

[project.entry-points.colrev]
search_source = "colrev.packages.synergy_datasets.src.synergy_datasets:SYNERGYDatasetsSearchSource"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
